name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * *'

jobs:
  CI:
    continue-on-error: ${{ matrix.kokkos_ver == 'develop' || matrix.distro == 'fedora:rawhide' || matrix.distro == 'opensuse:latest' || matrix.distro == 'ubuntu:devel' }} 
    strategy:
      matrix:
        distro: ['fedora:latest', 'fedora:rawhide', 'opensuse:latest', 'ubuntu:latest', 'ubuntu:devel', 'ubuntu:rolling']
        cxx: ['g++', 'clang++']
        openmp: ['ON', 'OFF']
        cmake_build_type: ['Debug', 'Release']
        kokkos_ver: ['3.2.01', 'master', 'develop']
        include:
          - distro: 'fedora:intel'
            cxx: 'icpc'
            openmp: 'ON'
            cmake_build_type: 'Release'
            kokkos_ver: 'master'
          - distro: 'fedora:intel'
            cxx: 'icpc'
            openmp: 'ON'
            cmake_build_type: 'Debug'
            kokkos_ver: 'master'
          - distro: 'fedora:intel'
            cxx: 'icpc'
            cmake_build_type: 'Release'
            openmp: 'OFF'
            kokkos_ver: 'master'
          - distro: 'fedora:intel'
            cxx: 'icpc'
            openmp: 'OFF'
            cmake_build_type: 'Debug'
            kokkos_ver: 'master'
    runs-on: ubuntu-20.04
    container: ghcr.io/kokkos/ci-containers/${{ matrix.distro }}
    steps:
      - name: Get trail license
        if: ${{ matrix.cxx == 'icpc' }}
        run: |
          mkdir ~/Licenses
          curl https://dynamicinstaller.intel.com/api/v2/license > ~/Licenses/intel.lic
      - name: Checkout kokkos
        uses: actions/checkout@v2.2.0
        with:
          repository: kokkos/kokkos
          ref: ${{ matrix.kokkos_ver }}
          path: kokkos
      - name: Build kokkos
        working-directory: kokkos
        run: |
          cmake -B build \
            -DCMAKE_INSTALL_PREFIX=$HOME/kokkos \
            -DKokkos_ENABLE_OPENMP=${{ matrix.openmp }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DKokkos_ENABLE_HWLOC=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
          cmake --build build --parallel 2
          cmake --install build
      - name: Checkout Cabana
        uses: actions/checkout@v2.2.0
      - name: Build Cabana
        run: |
          cmake -B build \
            -DCMAKE_INSTALL_PREFIX=$HOME/Cabana \
            -DCMAKE_PREFIX_PATH="$HOME/kokkos" \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_CXX_FLAGS='-Wall -pedantic --coverage' \
            -DCabana_ENABLE_TESTING=ON \
            -DCabana_ENABLE_EXAMPLES=ON \
            -DCabana_ENABLE_PERFORMANCE_TESTING=ON \
            -DCabana_PERFORMANCE_EXPECTED_FLOPS=0 \
            -DCMAKE_EXE_LINKER_FLAGS='--coverage' \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
          cmake --build build --parallel 2
          CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
          cmake --install build
      - name: Upload Report to codecov.io
        uses: codecov/codecov-action@v1
